# Test flaresim configuration
input           = ../build/output.exr
output          = ../build/flare_output.exr
lens            = lenses/doublegauss.lens
fov             = 90
rays            = 64
threshold       = 1.0
flare_gain      = 5000
